### PR TITLE
doc(README): Update badges

### PR DESCRIPTION
**Pull request by jhermsmeier**
This adds npm version, license, and download badges, while also normalising their style.

### CODE REVIEW

**Comment by jviotti** [comment]
Amazing stuff! Can you do this for the main Etcher repo as well?

**Comment by jhermsmeier** [comment]
@jviotti yeah, sure!

**Comment by lurch** [comment]
I wonder how many of the `5k downloads per month` are due to all the Ci builds? ;-)

**Comment by jviotti** [comment]
Shh, that's our little secret :P

**Pull request merged**
