### PR TITLE
chore(ci): Add CI deployment scripts

### PR DESCRIPTION
**Pull request by jhermsmeier**
This adds deployment step scripts for the prebuilds to
avoid the CIs accidentally exposing secrets through the logs.

Change-Type: patch

### CODE REVIEW

**Comment by jhermsmeier** [comment]
@hedss @lekkas is the above to be expected, or did something trip up here?

**Comment by lekkas** [comment]
@jhermsmeier looks like something tripped - VB added the changelog entry for `1.3.0`, also bumped the package.json to `1.3.0` but then attempted to tag with `v1.2.2`, which already exists. It's also strange as to why VB would create a minor `1.3.0` version given that the commit was marked as `patch` - the expected bumped version would be `1.2.3` I guess.

@jhermsmeier can you please open an issue in https://github.com/resin-io-modules/resin-procbots/ to make sure this does not get lost?

**Comment by lurch** [comment]
Looks like this might be the first time that VB has been used to merge a PR on this repo? Maybe there was something slightly-off with the formatting in CHANGELOG.md which caused VB's version-parsing to get confused?

**Comment by lurch** [comment]
Oh yes - it doesn't have the "standard header" in CHANGELOG.md which I guess means the skip-lines stuff would have gone wrong!

**Comment by jhermsmeier** [comment]
I copied the changelog template from the docs, but I guess I missed an already tagged version :/

**Comment by jhermsmeier** [comment]
Fixed it in https://github.com/resin-io-modules/mountutils/pull/53

**Comment by lekkas** [comment]
Good catch @lurch @jhermsmeier - that's right, VB needs a specific CHANGELOG.md header (i.e. the one at https://github.com/resin-io/process/blob/master/process/Commit_and_PR_Guidelines.md#versionbot-automatic-versioning-review-requirements-and-changelog-generation  )

**Comment by lurch** [comment]
I wonder if that's something that a future version of VB could check for @lekkas ?  (Or maybe that's just a nonsense-question)

**Comment by jhermsmeier** [comment]
I reckon it could just check for the first occurrence of a version header (i.e. match for `## vx.x.x - YYYY-MM-DD`) – that'd also allow for some customisation in the header.

**Comment by lurch** [comment]
Interesting idea @jhermsmeier - I created https://github.com/resin-io/versionist/issues/95

**Pull request merged**
