### PR TITLE
chore(CHANGELOG): Fix changelog formatting

### PR DESCRIPTION
**Pull request by jhermsmeier**
This fixes the CHANGELOG.md format, which got mangled a bit
with a previous version tag.

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
The header is still wrong. https://github.com/resin-io/process/blob/master/process/Commit_and_PR_Guidelines.md#versionbot-automatic-versioning-review-requirements-and-changelog-generation says:
```
# Change Log

All notable changes to this project will be documented in this file
automatically by Versionist. DO NOT EDIT THIS FILE MANUALLY!
This project adheres to [Semantic Versioning](http://semver.org/).

## v1.0.0 - <date in YYYY-MM-DD format>
````

but here you're using:
```
# Change Log

All notable changes to this project will be documented in this file.
This project adheres to [Semantic Versioning](http://semver.org/).

## v1.3.0 - 2017-10-13
```

Note the different number of "comment lines" - that's what I meant by the skip-lines stuff in #50

**Comment by jhermsmeier** [comment]
Whoops, fixed now!

**Comment by lurch** [comment]
Yep, looks better. Are we sticking with 1.3.0 then, rather than "fixing" it back to 1.2.3?

**Comment by jhermsmeier** [comment]
> Are we sticking with 1.3.0 then, rather than "fixing" it back to 1.2.3?

Yeah, I'd suggest we do, as it's already tagged etc.

**Comment by lurch** [comment]
P.S. How come https://github.com/resin-io-modules/mountutils/releases only lists the Windows builds?

**Comment by jhermsmeier** [comment]
That's because the tag builds on Linux didn't deploy (#52 fixes that)

**Pull request merged**
