### PR TITLE
chore(scripts): Also prebuild x86 on Windows and Linux

### PR DESCRIPTION
**Pull request by jhermsmeier**
Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
Is this the right way to do this, rather than running both x86 and x64 builds on Travis & Appveyor, as we do currently for Etcher?

**Comment by lurch** [comment]
(and obviously we should be doing the same thing for drivelist too)

**Comment by jhermsmeier** [comment]
> rather than running both x86 and x64 builds on Travis & Appveyor

That's exactly what this is doing.

> and obviously we should be doing the same thing for drivelist too

No need to state the obvious ;P Yeah, just wanted to do this one first in case it blows – don't have to fix two things then :)

**Comment by lurch** [comment]
> That's exactly what this is doing.

Nah, I meant the 'matrix' thing that Etcher does (so that the whole CI test runs on an x86 box), rather than just running a "make the x86 binaries" on a x64 box. IYSWIM?!

**Comment by jhermsmeier** [comment]
I am stupid. ISWYM. Hmm, but that'll extend the time the builds run considerably, and this should do the job just as well (?)

**Comment by lurch** [comment]
\*shrug\* Up to you - I guess it depends how "complete" we want our CI testing to be? ;-)  _Hopefully_ there won't be any problems in 32-bit builds that aren't picked up by our 64-bit tests?

I'll approve this then, and leave the final decision up to you... (but quickly pinging @jviotti , in case he has any opinions)

**Comment by jhermsmeier** [comment]
Yeah, let's see how this works out, and if it doesn't, go to doing x86 CI builds

**Comment by jhermsmeier** [comment]
@lurch looks like you're right – the x64 & x86 prebuilds are the exact same binary. This didn't do what I thought it'd do. On to proper x86 builds then.

**Pull request merged**
