### PR TITLE
chore(scripts): Run CI on x86 as well

### PR DESCRIPTION
**Pull request by jhermsmeier**
As previous efforts have shown, the `--arch` flags on `prebuild`
didn't do the expected, and this now runs CI builds on x86 as well.

Change-Type: patch
Connects To: #57

### CODE REVIEW

**Comment by lurch** [comment]
Just out of curiosity, I did a quick search in the `prebuild` repo, and AFAICT the `arch` is only actually used when constructing the output filename :-/

**Comment by lurch** [comment]
Do we need to restrict this to not run x86 builds on OSX? See https://github.com/resin-io/etcher/blob/master/.travis.yml for comparison.

**Comment by lurch** [comment]
Wow, such combinations! https://github.com/resin-io-modules/mountutils/releases/tag/v1.3.4
(but it seems like even that list isn't quite complete, as it's missing win32 x86 builds). Reminds me of @jviotti 's Contracts stuff! :laughing:

**Comment by jhermsmeier** [comment]
> and AFAICT the arch is only actually used when constructing the output filename :-/

Yeah, also saw that :'(

> Do we need to restrict this to not run x86 builds on OSX?

Whooops, fixed!

> but it seems like even that list isn't quite complete, as it's missing win32 x86 builds

Maybe this time around -.-

**Comment by lurch** [comment]
> Maybe this time around -.-

Fingers crossed... :-)

**Comment by lurch** [comment]
\*sigh\* https://travis-ci.org/resin-io-modules/mountutils/builds/290161226 claims it's run Linux x86 and Linux x64 builds, and https://ci.appveyor.com/project/resin-io/mountutils/build/1.0.328 claims it's run Windows x86 and x64 builds, but https://github.com/resin-io-modules/mountutils/releases shows no x86 builds for **v1.3.5** :cry:  

Hmmm, and https://ci.appveyor.com/project/resin-io/mountutils/build/1.0.328/job/f74jrkub2sst6l7h says `TARGET_ARCH=x86` but then:
```
Install-Product node $env:nodejs_version x64
Uninstalling node 4.8.4 (x86)...
Installing node 6.11.3 (x64)...
```
and later on
```
prebuild info begin Prebuild version 6.2.2
prebuild info build Preparing to prebuild mountutils@1.3.5 for node 4.6.1 on win32-x64 using node-gyp
```

Why does this have to be so tricky? :confounded: 

.....

Hmmm, just checked the [Appveyor docs](https://www.appveyor.com/docs/build-configuration/#build-matrix), and it says we need to use `platform` to change the CPU? Does this also mean that our Appveyor x86 builds on Etcher aren't set up correctly, @jviotti ?

I couldn't find anything in the Travis docs about x86 builds (although I found https://github.com/travis-ci/travis-ci/issues/986 ) and it looks like our Linux x86 builds of Etcher rely purely on running a 32-bit docker container on a 64-bit host.

Sorry @jhermsmeier , I didn't realise such a "simple request" https://github.com/resin-io-modules/mountutils/pull/57#issuecomment-337246097 would turn out to be so complicated :-/

**Pull request merged**
